-- Generated by nwg-displays on 2026-07-22 at 16:25:01. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1079@60.03",
    position = "4932x2160",
    scale = 1.0
})
hl.monitor({
    output = "DP-3",
    mode = "1920x1080@60.0",
    position = "7492x1080",
    scale = 1.0
})
hl.monitor({
    output = "DP-4",
    mode = "1920x1080@60.0",
    position = "3852x720",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@59.95",
    position = "4932x720",
    scale = 1.0
})
